# Generated by Django 3.2.19 on 2023-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_users", "0006_change_error_wording_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="get_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether you want to receive notifications. Select if you want to receive notifications.",
                verbose_name="Send me email notifications",
            ),
        ),
    ]
